import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

// The close reading of the open paper (§3), written module by module.
//
// Nine parts, each generated by its own call and each stored on its own,
// so a part that came out thin can be rewritten without paying for the
// other eight. Everything here is rendered from the structured result --
// the same claim-with-provenance shape the quick interpretation uses --
// so every statement says where it came from and the little page chips
// beside it are citations that have been checked against the paragraph
// they name. Clicking one jumps the PDF and the paragraph list to it.
//
// This is a piece of a pane rather than a pane: the caller supplies the
// scroll area and the margins, and connects the three signals below.
ColumnLayout {
    id: root

    // page is 1-based (as shown to the reader); blockId identifies the
    // paragraph, which is what actually gets scrolled to.
    signal evidenceRequested(int page, int blockId)
    signal askAiRequested(string text)
    signal compareRequested(string text)

    property int fs: settings.summaryFontSize

    // Which modules are open, keyed by id. A module the reader has not
    // touched is missing from here and follows the default -- only the
    // first one starts open, since nine expanded parts is a wall.
    property var openById: ({})

    // module(), moduleBusy() and moduleError() are plain calls: they carry
    // no change notification of their own, so nothing that reads one would
    // ever re-evaluate. Every such binding goes through the helpers below
    // and passes `rev`, which the service's deepChanged bumps -- that read
    // is what ties the binding to the signal.
    property int rev: 0

    spacing: 10

    Connections {
        target: analysis
        function onDeepChanged() {
            root.rev = root.rev + 1
            // A part being written opens itself, and stays open once it
            // lands -- collapsing it the moment it finished would hide the
            // thing the reader was waiting for.
            const ids = analysis.moduleIds
            let next = null
            for (let i = 0; i < ids.length; ++i) {
                const id = ids[i]
                if (analysis.moduleBusy(id) && root.openById[id] !== true) {
                    if (!next)
                        next = Object.assign({}, root.openById)
                    next[id] = true
                }
            }
            // A fresh object, not a mutation: a `var` property only
            // notifies when it is assigned.
            if (next)
                root.openById = next
        }
    }

    // ── reading the service ─────────────────────────────────────────
    // `rev` is unused in the bodies on purpose; see the note above.
    function moduleOf(id, rev) {
        const m = analysis.module(id)
        return m ? m : ({})
    }
    function isWritten(id, rev) {
        const m = analysis.module(id)
        return !!(m && Object.keys(m).length > 0)
    }
    function isBusy(id, rev) {
        return analysis.moduleBusy(id) === true
    }
    function errorOf(id, rev) {
        const e = analysis.moduleError(id)
        return e ? e : ""
    }
    function isOpen(id, index, rev) {
        if (root.isBusy(id, rev))
            return true
        const v = root.openById[id]
        return v === undefined ? index === 0 : v === true
    }
    function toggle(id, index) {
        const cur = root.openById[id] === undefined ? (index === 0)
                                                    : root.openById[id] === true
        let next = Object.assign({}, root.openById)
        next[id] = !cur
        root.openById = next
    }
    function stateHint(id, rev) {
        if (root.isBusy(id, rev))
            return qsTr("writing…")
        if (root.errorOf(id, rev).length > 0)
            return qsTr("failed")
        if (!root.isWritten(id, rev))
            return qsTr("not written")
        const m = root.moduleOf(id, rev).meta
        if (m && m.evidenceTotal > 0)
            return qsTr("%1 of %2 citations check out")
                   .arg(m.evidenceVerified ? m.evidenceVerified : 0)
                   .arg(m.evidenceTotal)
        return ""
    }

    // ── small shared helpers ────────────────────────────────────────
    // A single claim rendered as a one-item list, so coreQuestion and the
    // like go through the same path as conclusions.
    function one(claim) {
        return claim ? [claim] : []
    }
    function statusLabel(code) {
        switch (code) {
        case "available": return qsTr("available")
        case "partial":   return qsTr("partial")
        case "absent":    return qsTr("absent")
        default:          return qsTr("unclear")
        }
    }
    function statusColor(code) {
        switch (code) {
        case "available": return Theme.success
        case "absent":    return Theme.danger
        default:          return Theme.dimText   // partial / unclear
        }
    }
    function whenLabel(iso) {
        if (!iso)
            return ""
        const d = new Date(iso)
        return isNaN(d.getTime()) ? iso
                                  : d.toLocaleString(Qt.locale(), Locale.ShortFormat)
    }

    // ── small shared pieces ─────────────────────────────────────────
    component Chip: Rectangle {
        id: chip
        property string label: ""
        property color tint: Theme.dimText
        property string hint: ""
        implicitWidth: chipText.implicitWidth + 12
        implicitHeight: root.fs + 6
        radius: height / 2
        color: Qt.alpha(chip.tint, Theme.dark ? 0.22 : 0.13)
        border.color: Qt.alpha(chip.tint, 0.5)
        Label {
            id: chipText
            anchors.centerIn: parent
            text: chip.label
            color: chip.tint
            font.pixelSize: root.fs - 2
        }
        ToolTip.visible: chipHover.hovered && chip.hint.length > 0
        ToolTip.text: chip.hint
        ToolTip.delay: 400
        HoverHandler { id: chipHover }
    }

    component GroupTitle: Label {
        Layout.fillWidth: true
        wrapMode: Text.Wrap
        color: Theme.heading
        font.bold: true
        font.pixelSize: root.fs
    }

    // A labelled run of claims. Every claim in the close reading goes
    // through ClaimBlock, so the evidence chips and the §5 follow-ups
    // behave the same wherever they appear.
    component ClaimList: ColumnLayout {
        id: cl
        property string heading: ""
        property var claims: []
        property string moduleId: ""
        Layout.fillWidth: true
        spacing: 3
        visible: !!(cl.claims && cl.claims.length > 0)
        GroupTitle {
            visible: cl.heading.length > 0
            text: cl.heading
        }
        Repeater {
            model: cl.claims ? cl.claims : []
            delegate: ClaimBlock {
                required property var modelData
                Layout.fillWidth: true
                claim: modelData
                fs: root.fs
                onEvidenceRequested: (page, blockId) => root.evidenceRequested(page, blockId)
                onAskAiRequested: (text) => root.askAiRequested(text)
                onCompareRequested: (text) => root.compareRequested(text)
                onNoteRequested: (text) => analysis.saveNote(text, cl.moduleId)
            }
        }
    }

    component BulletList: ColumnLayout {
        id: bl
        property string heading: ""
        property var items: []
        Layout.fillWidth: true
        spacing: 2
        visible: !!(bl.items && bl.items.length > 0)
        GroupTitle {
            visible: bl.heading.length > 0
            text: bl.heading
        }
        Repeater {
            model: bl.items ? bl.items : []
            delegate: Label {
                required property var modelData
                Layout.fillWidth: true
                wrapMode: Text.Wrap
                color: Theme.text
                font.pixelSize: root.fs
                text: "• " + (modelData ? modelData : "")
            }
        }
    }

    // ── §3.1 what this paper is ─────────────────────────────────────
    component BasicsPart: ColumnLayout {
        id: basics
        property var mod: ({})
        property string moduleId: ""
        Layout.fillWidth: true
        spacing: 6
        Flow {
            Layout.fillWidth: true
            spacing: 4
            Chip {
                visible: !!(basics.mod && basics.mod.field)
                label: basics.mod && basics.mod.field ? basics.mod.field : ""
                tint: Theme.heading
                hint: qsTr("The research area.")
            }
            Chip {
                visible: !!(basics.mod && basics.mod.paperType)
                label: basics.mod && basics.mod.paperType ? basics.mod.paperType : ""
                tint: Theme.accent
                hint: qsTr("What kind of paper this is.")
            }
        }
        ClaimList {
            heading: qsTr("The question it asks")
            claims: root.one(basics.mod ? basics.mod.coreQuestion : null)
            moduleId: basics.moduleId
        }
        ClaimList {
            heading: qsTr("What it concludes")
            claims: basics.mod ? basics.mod.conclusions : []
            moduleId: basics.moduleId
        }
        ClaimList {
            heading: qsTr("Where it sits")
            claims: root.one(basics.mod ? basics.mod.positioning : null)
            moduleId: basics.moduleId
        }
    }

    // ── §3.2 background & terminology ───────────────────────────────
    component BackgroundPart: ColumnLayout {
        id: bg
        property var mod: ({})
        property string moduleId: ""
        Layout.fillWidth: true
        spacing: 6
        ColumnLayout {
            Layout.fillWidth: true
            spacing: 6
            visible: !!(bg.mod && bg.mod.terms && bg.mod.terms.length > 0)
            GroupTitle { text: qsTr("Terms you need first") }
            Repeater {
                model: bg.mod && bg.mod.terms ? bg.mod.terms : []
                delegate: ColumnLayout {
                    required property var modelData
                    Layout.fillWidth: true
                    spacing: 1
                    Label {
                        Layout.fillWidth: true
                        wrapMode: Text.Wrap
                        color: Theme.text
                        font.bold: true
                        font.pixelSize: root.fs
                        text: modelData.term ? modelData.term : ""
                    }
                    Label {
                        Layout.fillWidth: true
                        Layout.leftMargin: 10
                        wrapMode: Text.Wrap
                        color: Theme.bodyText
                        font.pixelSize: root.fs
                        visible: text.length > 0
                        text: modelData.plain ? modelData.plain : ""
                    }
                    Label {
                        Layout.fillWidth: true
                        Layout.leftMargin: 10
                        wrapMode: Text.Wrap
                        color: Theme.dimText
                        font.pixelSize: root.fs - 1
                        visible: !!modelData.roleInPaper
                        text: qsTr("In this paper: %1")
                              .arg(modelData.roleInPaper ? modelData.roleInPaper : "")
                    }
                }
            }
        }
        BulletList {
            heading: qsTr("Worth learning first")
            items: bg.mod ? bg.mod.prerequisites : []
        }
    }

    // ── §3.3 method ─────────────────────────────────────────────────
    component MethodPart: ColumnLayout {
        id: mth
        property var mod: ({})
        property string moduleId: ""
        Layout.fillWidth: true
        spacing: 6
        BulletList {
            heading: qsTr("What goes in")
            items: mth.mod ? mth.mod.inputs : []
        }
        BulletList {
            heading: qsTr("What comes out")
            items: mth.mod ? mth.mod.outputs : []
        }
        ColumnLayout {
            Layout.fillWidth: true
            spacing: 4
            visible: !!(mth.mod && mth.mod.steps && mth.mod.steps.length > 0)
            GroupTitle { text: qsTr("Step by step") }
            Repeater {
                model: mth.mod && mth.mod.steps ? mth.mod.steps : []
                delegate: RowLayout {
                    required property var modelData
                    required property int index
                    Layout.fillWidth: true
                    spacing: 6
                    ClaimBlock {
                        Layout.fillWidth: true
                        fs: root.fs
                        bullet: (index + 1) + ". "
                        // A step is not a claim of its own -- it is the
                        // model's walk-through -- but it cites paragraphs
                        // like one, so it is rendered like one.
                        claim: ({"text": modelData.step ? modelData.step : "",
                                 "evidence": modelData.evidence ? modelData.evidence : []})
                        onEvidenceRequested: (page, blockId) => root.evidenceRequested(page, blockId)
                        onAskAiRequested: (text) => root.askAiRequested(text)
                        onCompareRequested: (text) => root.compareRequested(text)
                        onNoteRequested: (text) => analysis.saveNote(text, mth.moduleId)
                    }
                    Chip {
                        Layout.alignment: Qt.AlignTop
                        label: modelData.novel === true ? qsTr("new here")
                                                        : qsTr("prior work")
                        tint: modelData.novel === true ? Theme.accent : Theme.dimText
                        hint: modelData.novel === true
                              ? qsTr("This step is the paper's own contribution.")
                              : qsTr("This step is taken from earlier work.")
                    }
                }
            }
        }
        ColumnLayout {
            Layout.fillWidth: true
            spacing: 2
            visible: !!(mth.mod && mth.mod.workedExample)
            GroupTitle { text: qsTr("A worked example") }
            Label {
                Layout.fillWidth: true
                wrapMode: Text.Wrap
                color: Theme.bodyText
                font.pixelSize: root.fs
                text: mth.mod && mth.mod.workedExample ? mth.mod.workedExample : ""
            }
        }
    }

    // ── §3.4 experiments ────────────────────────────────────────────
    component ExperimentsPart: ColumnLayout {
        id: exp
        property var mod: ({})
        property string moduleId: ""
        readonly property var setup: mod && mod.setup ? mod.setup : null
        readonly property var coverage: mod && mod.coverage ? mod.coverage : null
        Layout.fillWidth: true
        spacing: 6
        BulletList {
            heading: qsTr("Datasets / environments")
            items: exp.setup ? exp.setup.datasets : []
        }
        BulletList {
            heading: qsTr("Compared against")
            items: exp.setup ? exp.setup.baselines : []
        }
        BulletList {
            heading: qsTr("Metrics")
            items: exp.setup ? exp.setup.metrics : []
        }
        BulletList {
            heading: qsTr("What each metric measures")
            items: exp.setup ? exp.setup.metricMeanings : []
        }
        ColumnLayout {
            Layout.fillWidth: true
            spacing: 4
            visible: !!exp.coverage
            GroupTitle { text: qsTr("What the experiments cover") }
            Flow {
                Layout.fillWidth: true
                spacing: 4
                Repeater {
                    model: {
                        const c = exp.coverage
                        if (!c)
                            return []
                        return [
                            {"name": qsTr("ablation"),       "on": c.ablation === true},
                            {"name": qsTr("robustness"),     "on": c.robustness === true},
                            {"name": qsTr("generalization"), "on": c.generalization === true},
                            {"name": qsTr("efficiency"),     "on": c.efficiency === true}
                        ]
                    }
                    delegate: Chip {
                        required property var modelData
                        label: (modelData.on ? "✓ " : "✗ ") + modelData.name
                        tint: modelData.on ? Theme.success : Theme.dimText
                        hint: modelData.on ? qsTr("The paper reports this.")
                                           : qsTr("Nothing in the paper reports this.")
                    }
                }
            }
        }
        ClaimList {
            heading: qsTr("Do the experiments back the conclusions?")
            claims: root.one(exp.mod ? exp.mod.supportsConclusions : null)
            moduleId: exp.moduleId
        }
    }

    // ── §3.5 contributions ──────────────────────────────────────────
    component ContributionsPart: ColumnLayout {
        id: con
        property var mod: ({})
        property string moduleId: ""
        Layout.fillWidth: true
        spacing: 6
        ClaimList {
            // ClaimBlock already labels each one by kind, so no heading:
            // the section title says what these are.
            claims: con.mod ? con.mod.contributions : []
            moduleId: con.moduleId
        }
    }

    // ── §3.6 critical reading ───────────────────────────────────────
    component CritiquePart: ColumnLayout {
        id: crit
        property var mod: ({})
        property string moduleId: ""
        Layout.fillWidth: true
        spacing: 6
        Repeater {
            model: crit.mod && crit.mod.dimensions ? crit.mod.dimensions : []
            // Each dimension is already claim-shaped and carries a
            // verdict, which ClaimBlock knows how to show.
            delegate: ClaimList {
                required property var modelData
                heading: modelData.dimension ? modelData.dimension : ""
                claims: [modelData]
                moduleId: crit.moduleId
            }
        }
    }

    // ── §3.7 limitations ────────────────────────────────────────────
    component LimitationsPart: ColumnLayout {
        id: lim
        property var mod: ({})
        property string moduleId: ""
        Layout.fillWidth: true
        spacing: 8
        // Four groups, kept apart on purpose: what the authors own up to
        // and what they leave unsaid are read very differently.
        ClaimList {
            heading: qsTr("The authors admit")
            claims: lim.mod ? lim.mod.acknowledged : []
            moduleId: lim.moduleId
        }
        ClaimList {
            heading: qsTr("They do not raise")
            claims: lim.mod ? lim.mod.additional : []
            moduleId: lim.moduleId
        }
        ClaimList {
            heading: qsTr("Threats to validity")
            claims: lim.mod ? lim.mod.validityRisks : []
            moduleId: lim.moduleId
        }
        ClaimList {
            heading: qsTr("Cost, privacy and deployment")
            claims: lim.mod ? lim.mod.practical : []
            moduleId: lim.moduleId
        }
    }

    // ── §3.8 reproducibility ────────────────────────────────────────
    component ReproPart: ColumnLayout {
        id: rep
        property var mod: ({})
        property string moduleId: ""
        Layout.fillWidth: true
        spacing: 6
        ColumnLayout {
            Layout.fillWidth: true
            spacing: 4
            visible: !!(rep.mod && rep.mod.checklist && rep.mod.checklist.length > 0)
            GroupTitle { text: qsTr("What a reproduction would need") }
            Repeater {
                model: rep.mod && rep.mod.checklist ? rep.mod.checklist : []
                delegate: ColumnLayout {
                    required property var modelData
                    Layout.fillWidth: true
                    spacing: 1
                    RowLayout {
                        Layout.fillWidth: true
                        spacing: 6
                        Label {
                            Layout.alignment: Qt.AlignTop
                            Layout.minimumWidth: root.fs * 5
                            text: root.statusLabel(modelData.status)
                            color: root.statusColor(modelData.status)
                            font.bold: true
                            font.pixelSize: root.fs - 1
                        }
                        Label {
                            Layout.fillWidth: true
                            Layout.minimumWidth: 0
                            wrapMode: Text.Wrap
                            color: Theme.text
                            font.pixelSize: root.fs
                            text: modelData.what ? modelData.what : ""
                        }
                    }
                    ClaimBlock {
                        Layout.fillWidth: true
                        Layout.leftMargin: root.fs * 5 + 6
                        visible: !!(modelData.detail
                                    || (modelData.evidence
                                        && modelData.evidence.length > 0))
                        fs: root.fs - 1
                        bullet: ""
                        claim: ({"text": modelData.detail ? modelData.detail : "",
                                 "evidence": modelData.evidence ? modelData.evidence : []})
                        onEvidenceRequested: (page, blockId) => root.evidenceRequested(page, blockId)
                        onAskAiRequested: (text) => root.askAiRequested(text)
                        onCompareRequested: (text) => root.compareRequested(text)
                        onNoteRequested: (text) => analysis.saveNote(text, rep.moduleId)
                    }
                }
            }
        }
        BulletList {
            heading: qsTr("What would stop someone reproducing it")
            items: rep.mod ? rep.mod.blockers : []
        }
    }

    // ── §3.9 what to do next ────────────────────────────────────────
    component FollowupsPart: ColumnLayout {
        id: fup
        property var mod: ({})
        property string moduleId: ""
        Layout.fillWidth: true
        spacing: 8
        BulletList {
            heading: qsTr("Still unanswered")
            items: fup.mod ? fup.mod.openQuestions : []
        }
        BulletList {
            heading: qsTr("Worth putting to the authors or your advisor")
            items: fup.mod ? fup.mod.advisorQuestions : []
        }
        BulletList {
            heading: qsTr("Where this could go")
            items: fup.mod ? fup.mod.directions : []
        }
        BulletList {
            heading: qsTr("Small experiments that would test it")
            items: fup.mod ? fup.mod.minimalExperiments : []
        }
        BulletList {
            heading: qsTr("Read these next")
            items: fup.mod ? fup.mod.references : []
        }
    }

    // ── the strip across the top ────────────────────────────────────
    RowLayout {
        Layout.fillWidth: true
        // Breathing room under the tab bar: the button was sitting flush
        // against it.
        Layout.topMargin: 10
        Layout.bottomMargin: 2
        spacing: 8

        Label {
            Layout.fillWidth: true
            Layout.minimumWidth: 0
            elide: Text.ElideRight
            color: Theme.dimText
            font.pixelSize: root.fs - 1
            text: qsTr("%1 of %2 written").arg(analysis.deepDone)
                                          .arg(analysis.deepTotal)
        }
        BusyIndicator {
            running: analysis.deepRunning
            visible: running
            Layout.preferredWidth: 16
            Layout.preferredHeight: 16
        }
        AppButton {
            // Once all nine are written there is nothing left to continue;
            // rewriting lives in the ⋯ menu, where it cannot be hit by
            // accident.
            visible: analysis.deepRunning || analysis.deepDone < analysis.deepTotal
            enabled: analysis.deepRunning || analysis.canRun
            primary: true
            text: analysis.deepRunning
                  ? qsTr("Cancel")
                  : (analysis.deepDone > 0 ? qsTr("Continue")
                                           : qsTr("Read closely"))
            onClicked: {
                if (analysis.deepRunning)
                    analysis.cancelDeep()
                else
                    analysis.generateDeep(false)
            }
        }
        ToolButton {
            text: "⋯"
            onClicked: deepMenu.popup()
            Menu {
                id: deepMenu
                MenuItem {
                    text: qsTr("Rewrite everything")
                    enabled: analysis.canRun && !analysis.deepRunning
                    onTriggered: analysis.generateDeep(true)
                }
                MenuItem {
                    text: qsTr("Discard this close reading")
                    enabled: analysis.hasDeep && analysis.deepIsMine
                    onTriggered: analysis.discardDeep()
                }
            }
        }
    }

    // ── notices ─────────────────────────────────────────────────────
    Rectangle {
        Layout.fillWidth: true
        Layout.preferredHeight: noticeCol.implicitHeight + 10
        // Spelled out rather than derived from the children: `children` is
        // not a JS array, so there is nothing to fold over.
        visible: !!(analysis.deepStale
                    || (analysis.hasDeep && !analysis.deepIsMine)
                    || (analysis.hasDeep && !analysis.deepSaved))
        color: Theme.cardBg
        radius: Theme.radiusS
        ColumnLayout {
            id: noticeCol
            anchors.left: parent.left
            anchors.right: parent.right
            anchors.verticalCenter: parent.verticalCenter
            anchors.leftMargin: 10
            anchors.rightMargin: 10
            spacing: 2

            Label {
                Layout.fillWidth: true
                visible: analysis.deepStale
                wrapMode: Text.Wrap
                color: Theme.danger
                font.pixelSize: root.fs - 1
                text: qsTr("The paper, the research profile or the model has "
                           + "changed since this was written — it may be out "
                           + "of date.")
            }
            Label {
                Layout.fillWidth: true
                visible: analysis.hasDeep && !analysis.deepIsMine
                wrapMode: Text.Wrap
                color: Theme.dimText
                font.pixelSize: root.fs - 1
                text: qsTr("Written by %1. Rewrite a part to make it your own.")
                      .arg(analysis.deepAuthorEmail)
            }
            Label {
                Layout.fillWidth: true
                visible: analysis.hasDeep && !analysis.deepSaved
                wrapMode: Text.Wrap
                color: Theme.dimText
                font.pixelSize: root.fs - 1
                text: qsTr("Not saved: sign in and pick a project you can write "
                           + "to, and close readings are kept and shared.")
            }
        }
    }

    // ── what this is, before there is anything to show ──────────────
    Label {
        Layout.fillWidth: true
        visible: !analysis.hasDeep && !analysis.deepRunning
        wrapMode: Text.Wrap
        color: Theme.dimText
        font.pixelSize: root.fs
        text: qsTr("A close reading works through the paper in nine parts — "
                   + "what it is, the background you need, the method, the "
                   + "experiments, the contributions, a critical look, the "
                   + "limitations, what reproducing it would take, and what "
                   + "to do next. Each part is written on its own, so you can "
                   + "redo one without redoing the rest.")
    }
    Label {
        Layout.fillWidth: true
        visible: !analysis.hasDeep && !profile.hasProfile
        wrapMode: Text.Wrap
        color: Theme.dimText
        font.pixelSize: root.fs - 1
        text: qsTr("Tip: fill in the project's research profile first (toolbar "
                   + "→ Profile). The critical reading and the follow-ups are "
                   + "written against it.")
    }

    // ── the nine parts ──────────────────────────────────────────────
    Repeater {
        model: analysis.moduleIds
        delegate: ColumnLayout {
            id: sec
            required property string modelData
            required property int index

            readonly property string moduleId: sec.modelData
            readonly property var mod: root.moduleOf(sec.moduleId, root.rev)
            readonly property bool written: root.isWritten(sec.moduleId, root.rev)
            readonly property bool busy: root.isBusy(sec.moduleId, root.rev)
            readonly property string err: root.errorOf(sec.moduleId, root.rev)
            readonly property bool open: root.isOpen(sec.moduleId, sec.index, root.rev)

            Layout.fillWidth: true
            spacing: 4

            // ── the header, which is also the toggle ────────────────
            ItemDelegate {
                Layout.fillWidth: true
                padding: 6
                onClicked: root.toggle(sec.moduleId, sec.index)
                contentItem: RowLayout {
                    spacing: 6
                    Label {
                        text: sec.open ? "▾" : "▸"
                        color: Theme.dimText
                        font.pixelSize: root.fs
                    }
                    Label {
                        text: analysis.moduleTitle(sec.moduleId)
                        color: Theme.heading
                        font.bold: true
                        font.pixelSize: root.fs
                        elide: Text.ElideRight
                        Layout.minimumWidth: 0
                    }
                    Label {
                        Layout.fillWidth: true
                        Layout.minimumWidth: 0
                        text: root.stateHint(sec.moduleId, root.rev)
                        color: sec.err.length > 0 ? Theme.danger : Theme.dimText
                        font.pixelSize: root.fs - 2
                        elide: Text.ElideRight
                    }
                    BusyIndicator {
                        running: sec.busy
                        visible: running
                        Layout.preferredWidth: 14
                        Layout.preferredHeight: 14
                    }
                    ToolButton {
                        text: "↻"
                        flat: true
                        padding: 2
                        font.pixelSize: root.fs
                        enabled: analysis.canRun && !sec.busy
                        ToolTip.visible: hovered
                        ToolTip.delay: 400
                        ToolTip.text: qsTr("Write this part again, on its own")
                        onClicked: analysis.regenerateModule(sec.moduleId)
                    }
                }
            }

            // ── the body ────────────────────────────────────────────
            ColumnLayout {
                Layout.fillWidth: true
                Layout.leftMargin: 12
                Layout.bottomMargin: 4
                spacing: 6
                visible: sec.open

                Label {
                    Layout.fillWidth: true
                    visible: sec.err.length > 0
                    wrapMode: Text.Wrap
                    color: Theme.danger
                    font.pixelSize: root.fs - 1
                    text: sec.err
                }
                Label {
                    Layout.fillWidth: true
                    visible: sec.busy && !sec.written
                    wrapMode: Text.Wrap
                    color: Theme.dimText
                    font.pixelSize: root.fs
                    text: qsTr("Writing this part now…")
                }
                Label {
                    Layout.fillWidth: true
                    visible: !sec.written && !sec.busy && sec.err.length === 0
                    wrapMode: Text.Wrap
                    color: Theme.dimText
                    font.pixelSize: root.fs
                    text: qsTr("Not written yet — use ↻ to write just this part.")
                }

                Label {
                    Layout.fillWidth: true
                    visible: text.length > 0
                    wrapMode: Text.Wrap
                    color: Theme.bodyText
                    font.pixelSize: root.fs
                    text: sec.mod && sec.mod.summary ? sec.mod.summary : ""
                }

                // What this part carries on top of the common shape.
                BasicsPart {
                    visible: sec.moduleId === "basics"
                    mod: sec.mod
                    moduleId: sec.moduleId
                }
                BackgroundPart {
                    visible: sec.moduleId === "background"
                    mod: sec.mod
                    moduleId: sec.moduleId
                }
                MethodPart {
                    visible: sec.moduleId === "method"
                    mod: sec.mod
                    moduleId: sec.moduleId
                }
                ExperimentsPart {
                    visible: sec.moduleId === "experiments"
                    mod: sec.mod
                    moduleId: sec.moduleId
                }
                ContributionsPart {
                    visible: sec.moduleId === "contributions"
                    mod: sec.mod
                    moduleId: sec.moduleId
                }
                CritiquePart {
                    visible: sec.moduleId === "critique"
                    mod: sec.mod
                    moduleId: sec.moduleId
                }
                LimitationsPart {
                    visible: sec.moduleId === "limitations"
                    mod: sec.mod
                    moduleId: sec.moduleId
                }
                ReproPart {
                    visible: sec.moduleId === "repro"
                    mod: sec.mod
                    moduleId: sec.moduleId
                }
                FollowupsPart {
                    visible: sec.moduleId === "followups"
                    mod: sec.mod
                    moduleId: sec.moduleId
                }

                // The common shape: sections of claims.
                Repeater {
                    model: sec.mod && sec.mod.sections ? sec.mod.sections : []
                    delegate: ClaimList {
                        required property var modelData
                        heading: modelData.heading ? modelData.heading : ""
                        claims: modelData.items ? modelData.items : []
                        moduleId: sec.moduleId
                    }
                }

                // provenance footer
                Label {
                    Layout.fillWidth: true
                    visible: text.length > 0
                    wrapMode: Text.Wrap
                    color: Theme.dimText
                    font.pixelSize: root.fs - 2
                    text: {
                        const m = sec.mod ? sec.mod.meta : null
                        if (!m)
                            return ""
                        let parts = []
                        if (m.evidenceTotal > 0)
                            parts.push(qsTr("%1 of %2 citations check out")
                                       .arg(m.evidenceVerified ? m.evidenceVerified : 0)
                                       .arg(m.evidenceTotal))
                        if (m.claimsDemoted > 0)
                            parts.push(qsTr("%1 statement(s) demoted to AI reading")
                                       .arg(m.claimsDemoted))
                        if (m.truncated === true)
                            parts.push(qsTr("the paper was too long to send in full"))
                        const when = root.whenLabel(m.generatedAt)
                        if (when.length > 0)
                            parts.push(when)
                        return parts.join(" · ")
                    }
                }
            }
        }
    }
}
